### ISSUE TITLE
Inaccuracy in the documentation of the POST create an invoice rule endpoint

### ISSUE THREAD

**Issue by alexbrahastoll** [myfreecomm/billimatic-client-ruby#31]
The documentation states (https://app.billimatic.com.br/docs/api#!/invoice_rules/API_V1_InvoiceRules_create_post_0) that the only required field for services is the `service_item_id`. However, when attempting to create an invoice rule by sending the following payload to the server we get a 422 Unprocessable Entity:

(Sandbox enviroment)
POST https://sandbox.billimatic.com.br/api/v1/contracts/9530/invoice_rules.json

```json
{
  "invoice_rule": {
	  "gross_value": 200.5,
	  "description": "Regra para Empresa A - R$ 200,50",
	  "additional_information": {
	    "title": "Regra para Empresa A - R$ 200,50",
	    "init_date": "01-06-2017",
	    "end_date": null,
	    "period_unit": "monthly",
	    "month_quantity": 1,
	    "accrual_month_quantity": "same_month"
	  },
	  "contract_id": 8988,
	  "nfe_body": "$DESCRICAO",
	  "charge_type": "day_number",
	  "management_type": "manual",
	  "receivables_additional_information": {
	    "day_number": 5
	  },
	  "services": [
	  	{
	  		"service_item_id": 350,
	  	}
	  ]
  }
}
```

Server response:

```json
422 Unprocessable Entity

{
    "errors": {
        "services.units": "deve ser numérico",
        "services.unit_value": "deve ser numérico"
    }
}
```

When retrying the request adding a `unit` and a `unit_value`, we get a successful response from the server.

**Comment by guilhermeFranco** [comment]
@alexbrahastoll You are totally correct. We'll fix the documentation asap. I'm closing this because it's not an issue on the client per se. Thanks !
